@host = http://localhost:5184

POST {{host}}/properties
Accept: application/json
X-Api-Version: 1.0
Content-Type: application/json

{
  "name": "Camilos House",
  "address": "Test address",
  "price": 4500,
  "codeInternal": "CTC01",
  "year": 2025,
  "idOwner": "01990F9B-309D-76EE-AD93-DDC1B1137179"
}
###
