@host = http://localhost:5184
@idProperty=019910da-3fea-7939-8ac9-3220044bafff

PUT {{host}}/properties/{{idProperty}}
Accept: application/json
X-Api-Version: 1.0
Content-Type: application/json

{
  "name": "Camilo's House",
  "address": "Stree 29",
  "price": 48500,
  "codeInternal": "CTC01",
  "year": 2025
}